configure.ac: Check for -pthread.
On Tru64, we need to build with -pthread to be allowed to include
pthread.h:

	pthread.h:339:4: error: #error "Please compile the module including pthread.h with -pthread"

Signed-off-by: Lennert Buytenhek <buytenh@wantstofly.org>